// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(BlCommerceDataContext))]
    [Migration("20230720022859_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The latest iPhone model with 5G technology",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
                            Price = 799.00m,
                            Title = "Apple iPhone 13"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The latest Samsung Galaxy model with 5G technology",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-5g-r.jpg",
                            Price = 799.99m,
                            Title = "Samsung Galaxy S21"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The latest Google Pixel model with 5G technology",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6.jpg",
                            Price = 699.00m,
                            Title = "Google Pixel 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
